version: '3'
services:
  neo4j:
    container_name: neo4j
    image: neo4j
    networks:
      - neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ~/volumes/neo4j/:/data/

networks:
  neo4j: