version: '3'
services:
  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server
    ports:
      - 39000:9000
      - 38123:8123
    networks:
      - clickhouse
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ~/volumes/clickhouse/:/var/lib/clickhouse
      - ./users.xml:/etc/clickhouse-server/users.xml
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

networks:
  clickhouse: