version: "3"
services:
  sonar:
    image: sonarqube:community
    container_name: sonarqube
    networks:
      - sonarqube
    ports:
      - 9900:9000
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql:sonarqube
      - SONAR_JDBC_USERNAME=jy
      - SONAR_JDBC_PASSWORD=123456
    volumes:
      - ~/volumes/sonarqube/data/:/opt/sonarqube/data/
      - ~/volumes/sonarqube/logs/:/opt/sonarqube/logs/
      - ~/volumes/sonarqube/extensions/:/opt/sonarqube/extensions/

networks:
  sonarqube: