version: '3'
services:
  caddy:
    container_name: caddy
    image: caddy:alpine
    restart: always
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/:/data/
      - ./config/:/config/