version: '3'
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ZOO_LOG4J_PROP="INFO,ROLLINGFILE"
    volumes:
      - ~/volumes/zookeeper/data/:/data/
      - ~/volumes/zookeeper/datalog/:/datalog/
      - ~/volumes/zookeeper/logs/:/logs/
    networks:
      - zk
networks:
  zk:
