version: '3'
services:
  rocketmq-nameservice:
    container_name: rocketmq-nameservice
    image: apache/rocketmq:4.9.4
    command: [ "sh","mqnamesrv" ]
    network_mode: host
    volumes:
      - ./nameservice/logs:/home/rocketmq/logs
      - ./nameservice/store:/home/rocketmq/store
    environment:
      - "JAVA_OPT_EXT=-Duser.home=/home/rocketmq -Xms2g -Xmx2g -Xmn1g"
  rocketmq-broker:
    container_name: rocketmq-broker
    image: apache/rocketmq:4.9.4
    command: [ "sh","mqbroker","-c","/etc/rocketmq/broker.conf","-n","localhost:9876" ]
    network_mode: host
    volumes:
      - ./broker/logs:/home/rocketmq/logs
      - ./broker/store:/home/rocketmq/store
      - ./broker.conf:/etc/rocketmq/broker.conf
    environment:
      - "JAVA_OPT_EXT=-Duser.home=/home/rocketmq -Xms2g -Xmx2g -Xmn1g"
    depends_on:
      - rocketmq-nameservice
  rocketmq-dashboard:
    container_name: rocketmq-dashboard
    image: apacherocketmq/rocketmq-dashboard
    network_mode: host
    environment:
      - "JAVA_OPTS=-Dserver.port=8084 -Drocketmq.namesrv.addr=localhost:9876"
    depends_on:
      - rocketmq-nameservice