global:
  resolve_timeout: 5m
  smtp_from: 'xx@qq.com'
  smtp_smarthost: 'smtp.qq.com:465'
  smtp_auth_username: 'xx@qq.com'
  smtp_auth_password: '***'
  smtp_require_tls: false

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'xx@qq.com'
