version: '3.7'
services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
            - /data/softs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - /data/softs/prometheus/:/prometheus/
        restart: always
        network_mode: host
