version: '3'
services:
    prometheus:
           image: prom/prometheus:v2.3.1
           container_name: prometheus
           ports:
              - 9090:9090
           volumes:
              - ~/volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
              - ~/volumes/prometheus/:/prometheus/
           networks:
              - prometheus

networks:
   prometheus:
