global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alertmanager_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["altermanager:9093"]

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
#  - job_name: 'demo-app'
#    metrics_path: /actuator/prometheus
#    static_configs:
#      - targets: ['192.168.0.18:8100']
