version: '3'
services:
        grafana:
                image: grafana/grafana:5.2.1
                container_name: grafana
                ports:
                    - 4000:3000
                networks:
                    - grafana
                volumes:
                    - /home/jy/volumes/grafana/:/var/lib/grafana
networks:
        grafana:
