version: '3'
services:
    app-rabbitmq:
      image: rabbitmq:3.7.7-management-alpine
      container_name: rabbitmq
      environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: rabbithlt
        RABBITMQ_DEFAULT_PASS: sonic333
        RABBITMQ_DEFAULT_VHOST: yiye_dev
      ports:
        - 15672:15672
        - 5672:5672
      networks:
        - rabbitmq
      volumes:
        - ~/volumes/rabbitmq/data/:/var/lib/rabbitmq/
networks:
    rabbitmq:
