version: '3'
services:
  ci-redis:
    image: redis
    volumes:
      - ~/volumes/redis/data/:/data
      - ~/volumes/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
  ci-postgresql:
    image: postgres:9.6.6
    volumes:
      - ~/volumes/postgresql/data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=sonic333
    ports:
      - 5432:5432
  ci-gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    hostname: gitlab.javaone.cc
    depends_on:
      - ci-redis
      - ci-postgresql
    ports:
      - "10080:80"
      - "10022:22"
    volumes:
      - ~/volumes/gitlab/config:/etc/gitlab
      - ~/volumes/gitlab/logs:/var/log/gitlab
      - ~/volumes/gitlab/data:/var/opt/gitlab
    environment:
      - DEBUG=false
      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=postgresuser
      - DB_PASS=sonic333
      - DB_NAME=gitlabhq_production

      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - TZ=Asia/Shanghai
      - GITLAB_TIMEZONE=Shanghai

      - GITLAB_HTTPS=false
      - SSL_SELF_SIGNED=false

      - GITLAB_HOST=localhost
      - GITLAB_PORT=80
      - GITLAB_SSH_PORT=22
      - GITLAB_RELATIVE_URL_ROOT=
      - GITLAB_SECRETS_DB_KEY_BASE=abc123123
      - GITLAB_SECRETS_SECRET_KEY_BASE=abc123123
      - GITLAB_SECRETS_OTP_KEY_BASE=abc123123

      - GITLAB_ROOT_PASSWORD=
      - GITLAB_ROOT_EMAIL=

      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
      - GITLAB_NOTIFY_PUSHER=false

      - GITLAB_EMAIL=977996067@qq.com
      - GITLAB_EMAIL_REPLY_TO=977996067@qq.com
      - GITLAB_INCOMING_EMAIL_ADDRESS=977996067@qq.com

      - GITLAB_BACKUP_SCHEDULE=daily
      - GITLAB_BACKUP_TIME=01:00

      - OAUTH_ENABLED=false
      - OAUTH_AUTO_SIGN_IN_WITH_PROVIDER=
      - OAUTH_ALLOW_SSO=
      - OAUTH_BLOCK_AUTO_CREATED_USERS=true
      - OAUTH_AUTO_LINK_LDAP_USER=false
      - OAUTH_AUTO_LINK_SAML_USER=false
      - OAUTH_EXTERNAL_PROVIDERS=

      - OAUTH_CAS3_LABEL=cas3
      - OAUTH_CAS3_SERVER=
      - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=false
      - OAUTH_CAS3_LOGIN_URL=/cas/login
      - OAUTH_CAS3_VALIDATE_URL=/cas/p3/serviceValidate
      - OAUTH_CAS3_LOGOUT_URL=/cas/logout

      - OAUTH_SAML_ISSUER=
      - OAUTH_SAML_LABEL="Our SAML Provider"
      - OAUTH_SAML_NAME_IDENTIFIER_FORMAT=urn:oasis:names:tc:SAML:2.0:nameid-format:transient
