apisix:
  node_listen: # APISIX listening ports.
    - 9080
  enable_admin: true           # Admin API
  enable_dev_mode: false       # If true, set nginx `worker_processes` to 1.
  enable_reuseport: true       # If true, enable nginx SO_REUSEPORT option.
  show_upstream_status_in_response_header: true  # If true, include the upstream HTTP status code in
    # the response header `X-APISIX-Upstream-Status`.
  # If false, show `X-APISIX-Upstream-Status` only if
  # the upstream response code is 5xx.
  enable_ipv6: false
  enable_http2: false
  stream_proxy:
    tcp:
      - 5672
      - 15672
  ssl:
    enable: false

  enable_control: false  # Control API

deployment: # Deployment configurations
  admin: # Admin API
    admin_key_required: true   # Enable Admin API authentication by default for security.
    admin_key:
      - name: admin                             # admin: write access to configurations.
        key: add1c9f034335f136f87ad84b625c8f1   # Set API key for the admin of Admin API.
        role: admin
  role: data_plane
  role_data_plane:
    config_provider: yaml