version: '3'
services:
  create_certs:
    container_name: es_certs
    image: elasticsearch:$VERSION
    command: >
      bash -c '
        if [[ ! -f /certs/bundle.zip ]]; then
          bin/elasticsearch-certutil ca --pem -out /certs/ca.zip --days 36500 -s;
          unzip /certs/ca.zip -d /certs;
          bin/elasticsearch-certutil cert -s --pem --ca-cert /certs/ca/ca.crt --ca-key /certs/ca/ca.key --in config/certificates/instances.yml -out /certs/bundle.zip;
          unzip /certs/bundle.zip -d /certs;
        fi;
        chown -R 1000:0 /certs
      '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes:
      - ./certs:/certs
      - ./instance.yml:/usr/share/elasticsearch/config/certificates/instances.yml