version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "8443:443"
    volumes:
      - ./:/etc/nginx/conf.d/
    networks:
      - nginx

networks:
  nginx: