version: "3"
services:
  nacos:
    image: nacos/nacos-server:1.2.0
    container_name: nacos-server
    network_mode: host
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
    volumes:
      - ~/volumes/nacos/standalone-logs/:/home/nacos/logs
      - ~/volumes/nacos/init.d/:/home/nacos/init.d/