version: '3'
services:
  graylog:
    image: graylog/graylog:4.0
    container_name: graylog
    volumes:
      - ./data/:/usr/share/graylog/data/
      - ./plugin/:/usr/share/graylog/plugin/
    network_mode: host