version: '2'
services:
    mongodb:
        image: mongo
        container_name: graylog_mongo
        volumes:
            - ~/volumes/graylog/mongo/:/data/db
        networks:
            - graylog
        ports:
            - 27017:27017
    elasticsearch:
        image: elasticsearch:6.8.1
        container_name: graylog_es
        volumes:
            - ~/volumes/graylog/es/:/usr/share/elasticsearch/data
        environment:
            - http.host=0.0.0.0
            - transport.host=localhost
            - network.host=0.0.0.0
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        networks:
            - graylog
        ports:
            - 9200:9200
            - 9300:9300
        ulimits:
            memlock:
                soft: -1
                hard: -1
        mem_limit: 3g
    graylog:
        image: graylog/graylog:3.0.2
        container_name: graylog
        volumes:
            - ~/volumes/graylog/journal/:/usr/share/graylog/data/journal
            - ./config:/usr/share/graylog/data/config
        links:
            - mongodb:mongo
            - elasticsearch
        depends_on:
            - mongodb
            - elasticsearch
        networks:
            - graylog
        ports:
            # Graylog web interface and REST API
            - 9000:9000
            # Syslog TCP
            - 1514:1514
            # Syslog UDP
            - 1514:1514/udp
            # GELF TCP
            - 12201:12201
            # GELF UDP
            - 12201:12201/udp

networks:
    graylog:
