version: '3'
services:
    mongodb:
        image: mongo
        container_name: graylog_mongo
        volumes:
            - ~/volumes/graylog/mongo/:/data/db
        networks:
            - graylog
        ports:
            - 27017:27017
    elasticsearch:
        image: elasticsearch:7.2.0
        container_name: graylog_es
        volumes:
            - ~/volumes/graylog/es/:/usr/share/elasticsearch/data
        environment:
            - http.host=0.0.0.0
            - transport.host=localhost
            - network.host=0.0.0.0
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        networks:
            - graylog
        ports:
            - 9200:9200
            - 9300:9300
        ulimits:
            memlock:
                soft: -1
                hard: -1
        mem_limit: 3g
    graylog:
        image: graylog/graylog:3.0.2
        container_name: graylog
        volumes:
            - ~/volumes/graylog/journal/:/usr/share/graylog/data/journal
        environment:
            - GRAYLOG_PASSWORD_SECRET=sonic333sonic333
            - GRAYLOG_ROOT_PASSWORD_SHA2=d4eda3a3dbe632df70e4412fa513b56817541b5022e341995538443ae936060a
            - GRAYLOG_HTTP_EXTERNAL_URI=http://0.0.0.0:9000/
        links:
            - mongodb:mongo
            - elasticsearch
        depends_on:
            - mongodb
            - elasticsearch
        networks:
            - graylog
        ports:
            # Graylog web interface and REST API
            - 9000:9000
            # Syslog TCP
            - 1514:1514
            # Syslog UDP
            - 1514:1514/udp
            # GELF TCP
            - 12201:12201
            # GELF UDP
            - 12201:12201/udp

networks:
    graylog:
