version: '3'
services:
  elk:
    image: sebp/elk:640
    container_name: elk
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044
      - 9300:9300
    environment:
      - "TZ=Asia/Shanghai"
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    volumes:
      - /mnt/data/elk/:/var/lib/elasticsearch
    networks:
      - elk

networks:
    elk:
