version: '3'
services:
  portainer:
    container_name: portainer
    restart: always
    image: portainer/portainer:1.19.2
    command: -H unix:///var/run/docker.sock
    ports:
      - 19000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/volumes/portainer/data:/data
    networks:
      - portainer
networks:
    portainer:

