version: '3'
services:
  portainer:
    container_name: portainer
    restart: always
    image: portainer/portainer-ce:alpine
    command: -H unix:///var/run/docker.sock
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/volumes/portainer/data:/data
