version: '3'
services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=123123
    container_name: mysql
    networks:
      - net-mysql
    ports:
      - 3306:3306
    image: mysql:8.0.11
    volumes:
      - ~/volumes/mysql/:/var/lib/mysql/

networks:
    net-mysql:
