version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=cw
    networks:
      - mysql
    ports:
      - 3306:3306
    volumes:
      - ~/volumes/mysql/:/var/lib/mysql/

networks:
  mysql: