version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=demo
    network_mode: host
    volumes:
      - ~/volumes/mysql/:/var/lib/mysql/
