version: '3'
services:
  ci-jenkins:
    image: jenkinsci/blueocean
    container_name: ci-jenkins
    user: root
    volumes:
      - ~/volumes/jenkins/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci
    ports:
      - 12580:8080
      - 50000:50000

  ci-redis:
    image: redis
    container_name: ci-redis
    networks:
      - ci
    ports:
      - 16379:6379
    command:
      - "--appendonly yes"
    volumes:
      - ~/volumes/gitlab/redis/:/var/lib/redis

  ci-postgresql:
    container_name: ci-postgresql
    image: postgres:9.6.8-alpine
    networks:
      - ci
    volumes:
      - ~/volumes/gitlab/postgresql/:/var/lib/postgresql
    ports:
      - 15432:5432
    environment:
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production
      - DB_EXTENSION=pg_trgm

  ci-gitlab:
    image: gitlab/gitlab-ce
    hostname: gitlab.javaone.cc
    container_name: ci-gitlab
    depends_on:
      - ci-postgresql
      - ci-redis
    ports:
      - "10080:80"
      - "10443:443"
      - "10022:22"
    networks:
      - ci
    volumes:
      - ~/volumes/gitlab/data:/var/opt/gitlab
      - ~/volumes/gitlab/config:/etc/gitlab
      - ~/volumes/gitlab/logs:/var/log/gitlab
    environment:
      - DEBUG=false

      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=15432
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production

      - REDIS_HOST=redis
      - REDIS_PORT=16379

      - TZ=Asia/Shanghai
      - GITLAB_TIMEZONE=Shanghai

      - GITLAB_HTTPS=false
      - SSL_SELF_SIGNED=false

      - GITLAB_HOST=gitlab.javaone.cc
      - GITLAB_PORT=80
      - GITLAB_SSH_PORT=22
      - GITLAB_RELATIVE_URL_ROOT=
      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
      - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alphanumeric-string
      - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alphanumeric-string

      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
      - GITLAB_NOTIFY_PUSHER=false

      - GITLAB_EMAIL=977996067@qq.com
      - GITLAB_EMAIL_REPLY_TO=977996067@qq.com
      - GITLAB_INCOMING_EMAIL_ADDRESS=977996067@qq.com

      - GITLAB_BACKUP_SCHEDULE=daily
      - GITLAB_BACKUP_TIME=01:00

      - SMTP_ENABLED=false
      - IMAP_ENABLED=false
      - OAUTH_ENABLED=false

      - OAUTH_CAS3_LABEL=cas3
      - OAUTH_CAS3_SERVER=
      - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=false
      - OAUTH_CAS3_LOGIN_URL=/cas/login
      - OAUTH_CAS3_VALIDATE_URL=/cas/p3/serviceValidate
      - OAUTH_CAS3_LOGOUT_URL=/cas/logout

networks:
  ci:
