version: '3'
services:
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    network_mode: host
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
    volumes:
      - ~/volumes/kafka/:/kafka
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    network_mode: host
    environment:
      - ZOO_LOG4J_PROP="INFO,ROLLINGFILE"
    volumes:
      - ~/volumes/zookeeper/data/:/data/
      - ~/volumes/zookeeper/datalog/:/datalog/
      - ~/volumes/zookeeper/logs/:/logs/
  kafka-gui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    environment:
      - SERVER_PORT=9192
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=localhost:9092
    network_mode: host