version: '2'
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - kafka
    volumes:
      - ~/volumes/zookeeper/data/:/data
      - ~/volumes/zookeeper/datalog/:/datalog
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    networks:
      - kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.124.32
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ~/volumes/kafka/:/kafka
networks:
  kafka: