version: '3'
services:
  postgresql:
    image: postgres:alpine
    container_name: postgresql
    volumes:
      - ~/volumes/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jy
      - POSTGRES_PASSWORD=123456
      - TZ=Asia/Shanghai
    network_mode: host
