version: '3'
services:
        influxdb:
                image: influxdb:1.6.0-alpine
                container_name: influxdb
                ports:
                        - 8086:8086
                        - 8083:8083
                        - 2003:2003  
                volumes:
                        - ~/volumes/influxdb/:/var/lib/influxdb/
                environment:
                        - INFLUXDB_GRAPHITE_ENABLED=true
                        - INFLUXDB_ADMIN_ENABLED=true
                        - INFLUXDB_ADMIN_USER=admin
                        - INFLUXDB_ADMIN_PASSWORD=123123
                networks:
                        - influxdb
networks:
         influxdb:        
