version: '3'
services:
  mongo:
    image: mongo:4.1.1
    container_name: mongodb
    networks:
      - mongo
    ports:
      - 27017:27017
    volumes:
      - ~/volumes/mongodb/data/:/data/db/

networks:
    mongo:
