version: '3.7'
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    network_mode: host
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data/:/data/
