version: '3'
services:
    redis:
        image: redis:alpine
        container_name: redis
        volumes:
            - ~/volumes/redis/data/:/data
        command: redis-server --appendonly yes
        network_mode: host
